apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: early-zebra-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: early-zebra-go 
  name: early-zebra-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: early-zebra-go 
